In [9]:
import pandas as pd
import seaborn as sns
from datetime import datetime
import matplotlib.pyplot as plt
import numpy as np

# Load the final_dataframe.csv into a DataFrame
final_df = pd.read_csv('final_dataframe.csv')
clients_df = pd.read_csv('clients_dataset.csv')
display(final_df)
display(final_df.dtypes)

,ClientID,ProductID,TransactionDate,StoreID,StoreCountry,Quantity_in_stock,Category,FamilyLevel1,FamilyLevel2,Universe,ClientSegment,ClientGender,Age,ClientCountry,ClientOptINEmail,ClientOptINPhone,Quantity_sold,SalesNetAmountEuro,product_avg_price_order,avg_price,Weekday
0,39370740138294,1440540189819119258,2024-12-17 00:00:00+00:00,7704230050291051317,GBR,0.0,Football,Jersey,Nike Away Jersey,Women,LOYAL,F,22.0,GBR,1,1,2,14.99,7.495000,8.337189,Tuesday
1,39370740138294,1830527890021285361,2024-10-27 00:00:00+00:00,4823099650757441528,GBR,0.0,Football,Shorts,Nike Dri-FIT,Women,LOYAL,F,22.0,GBR,1,1,1,13.99,13.990000,9.181570,Sunday
2,39370740138294,3095307643986324846,2024-10-28 00:00:00+00:00,4823099650757441528,GBR,0.0,Handball,Ball,Select Ultimate,Men,LOYAL,F,22.0,GBR,1,1,2,78.99,39.495000,53.883987,Monday
3,41168361649132,4786639895536460836,2024-03-03 00:00:00+00:00,7913334853958149044,FRA,3.0,Badminton,Racket,Yonex Astrox 99,Women,LOYAL,F,NaN,FRA,1,1,3,21.98,7.326667,9.759794,Sunday
4,118552773044620,7951360260357319889,2024-12-09 00:00:00+00:00,3306498059038628287,USA,1.0,Baseball,Glove,Wilson A2000,Men,LOYAL,F,52.0,USA,1,0,2,38.99,19.495000,26.422090,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
902003,9223352473445645109,1102195885428775766,2025-02-05 00:00:00+00:00,7072849857188684803,ARE,13.0,Badminton,Shuttlecock,Victor Gold Champion,Men,LOYAL,F,NaN,ARE,0,0,1,27.99,27.990000,16.059312,Wednesday
902004,9223352473445645109,5760088997185117368,2024-05-08 00:00:00+00:00,7072849857188684803,ARE,0.0,Tennis,Ball,Wilson US Open,Men,LOYAL,F,NaN,ARE,0,0,1,26.99,26.990000,15.618155,Wednesday
902005,9223352473445645109,5760088997185117368,2024-05-21 00:00:00+00:00,7072849857188684803,ARE,0.0,Tennis,Ball,Wilson US Open,Men,LOYAL,F,NaN,ARE,0,0,1,5.99,5.990000,15.618155,Tuesday
902006,9223352473445645109,5760088997185117368,2024-05-23 00:00:00+00:00,7072849857188684803,ARE,0.0,Tennis,Ball,Wilson US Open,Men,LOYAL,F,NaN,ARE,0,0,2,23.99,11.995000,15.618155,Thursday
902007,9223363787153601649,6542734401418447353,2024-12-03 00:00:00+00:00,3306498059038628287,USA,6.0,Badminton,Racket,Victor Thruster K,Women,LOYAL,M,NaN,USA,0,0,3,25.98,8.660000,8.876234,Tuesday

ClientID                     int64
ProductID                    int64
TransactionDate             object
StoreID                      int64
StoreCountry                object
Quantity_in_stock          float64
Category                    object
FamilyLevel1                object
FamilyLevel2                object
Universe                    object
ClientSegment               object
ClientGender                object
Age                        float64
ClientCountry               object
ClientOptINEmail             int64
ClientOptINPhone             int64
Quantity_sold                int64
SalesNetAmountEuro         float64
product_avg_price_order    float64
avg_price                  float64
Weekday                     object
dtype: object

In [10]:
final_df['TransactionDate'] = pd.to_datetime(final_df['TransactionDate'])
display(final_df.dtypes)

ClientID                                 int64
ProductID                                int64
TransactionDate            datetime64[ns, UTC]
StoreID                                  int64
StoreCountry                            object
Quantity_in_stock                      float64
Category                                object
FamilyLevel1                            object
FamilyLevel2                            object
Universe                                object
ClientSegment                           object
ClientGender                            object
Age                                    float64
ClientCountry                           object
ClientOptINEmail                         int64
ClientOptINPhone                         int64
Quantity_sold                            int64
SalesNetAmountEuro                     float64
product_avg_price_order                float64
avg_price                              float64
Weekday                                 object
dtype: object

In [11]:
# =============================================================================
# 1. Create a "Brand" column in final_df based on FamilyLevel2 using the mapping
# -----------------------------------------------------------------------------
brand_mapping = {
    "Nike Ordem V": "Nike",
    "Nike Dri-FIT": "Nike",
    "Adidas Telstar 18": "Adidas",
    "Adidas Home Jersey": "Adidas",
    "Adidas Squadra 21": "Adidas",
    "Adidas Predator": "Adidas",
    "Nike Away Jersey": "Nike",
    "Puma Future": "Puma",
    "Trek Domane SL7": "Trek",
    "Bell Super 3R MIPS": "Bell",
    "Giro Synthe MIPS": "Giro",
    "Kask Protone": "Kask",
    "Specialized S-Works Roubaix": "Specialized",
    "Giant TCR Advanced Pro": "Giant",
    "Victor Thruster K": "Victor",
    "Yonex AS-30": "Yonex",
    "Victor Gold Champion": "Victor",
    "Yonex Astrox 99": "Yonex",
    "Mizuno Wave Mirage": "Mizuno",
    "Select Ultimate": "Select",
    "Molten H3X5001": "Molten",
    "Asics Gel-Blast": "Asics",
    "Nike Mercurial Vapor": "Nike",
    "Puma Third Jersey": "Puma",
    "Penn Championship": "Penn",
    "Babolat Pure Drive": "Babolat",
    "Head Graphene 360+ Speed Pro": "Head",
    "Wilson US Open": "Wilson",
    "Wilson Pro Staff RF97": "Wilson",
    "Nike AeroBill Classic99": "Nike",
    "Titleist T100 Irons": "Titleist",
    "FootJoy Pro/SL": "FootJoy",
    "FootJoy WeatherSof": "FootJoy",
    "Callaway Chrome Soft": "Callaway",
    "Adidas CodeChaos": "Adidas",
    "Titleist Pro V1": "Titleist",
    "Callaway JAWS MD5 Wedges": "Callaway",
    "Warrior Alpha DX": "Warrior",
    "Warrior Covert PX+": "Warrior",
    "Bauer Nexus 2N Pro": "Bauer",
    "Mikasa V200W": "Mikasa",
    "Tachikara SV5WSC": "Tachikara",
    "Molten FLISTATEC": "Molten",
    "Rawlings Quatro Pro": "Rawlings",
    "Easton ADV 360": "Easton",
    "Nike Air Zoom BB NXT": "Nike",
    "Adidas Harden Vol. 4": "Adidas",
    "Wilson Evolution Basketball": "Wilson",
    "Spalding NBA Official Game Ball": "Spalding",
    "Under Armour Curry 7": "Under Armour",
    "CCM Fitlite": "CCM",
    "A&R Sports Ice Hockey Puck": "A&R Sports",
    "Green Biscuit Training Puck": "Green Biscuit",
    "Adidas Torpedo": "Adidas",
    "Canterbury Advantage": "Canterbury",
    "Rhino Vortex Elite": "Rhino",
    "Canterbury Vapodri": "Canterbury",
    "Adidas Rugby Shorts": "Adidas",
    "Adidas Performance": "Adidas",
    "Gilbert Omega": "Gilbert",
    "SS Test": "SS",
    "Bauer RE-AKT": "Bauer",
    "CCM Ribcor Trigger": "CCM",
    "Adidas Climalite": "Adidas",
    "New Balance Furon": "New Balance",
    "Arena Carbon Air2": "Arena",
    "Arena Cobra Ultra": "Arena",
    "Speedo Fastskin LZR Racer X": "Speedo",
    "DeMarini CF": "DeMarini",
    "Easton Ghost": "Easton",
    "Dudley Thunder Heat": "Dudley",
    "Worth Dream Seam": "Worth",
    "Puma Final 1": "Puma",
    "TaylorMade SIM2 Driver": "TaylorMade",
    "Nike Air Zoom Infinity Tour": "Nike",
    "Nike Streak": "Nike",
    "Wilson A2000": "Wilson",
    "Kookaburra Kahuna": "Kookaburra",
    "Titleist Tour Performance": "Titleist",
    "Callaway Dawn Patrol": "Callaway",
    "Rawlings Heart of the Hide": "Rawlings",
    "Puma EvoSpeed": "Puma",
    "TYR Blackhawk Racing": "TYR",
    "Mizuno LR6": "Mizuno",
    "Rawlings Official MLB": "Rawlings",
    "Speedo Vanquisher 2.0": "Speedo",
    "Wilson A1030": "Wilson",
    "Louisville Slugger Meta": "Louisville Slugger",
    "Under Armour Tech": "Under Armour",
    "Bridgestone Tour B XS": "Bridgestone",
    "Gray-Nicolls GN5": "Gray-Nicolls",
    "Masuri Vision Series": "Masuri",
    "Nike Flex Stride": "Nike",
    "TaylorMade Stratus Tech": "TaylorMade",
    "Shrey MasterClass": "Shrey",
    "Kookaburra Ghost": "Kookaburra",
    "SG Test": "SG",
    "Adidas Own The Run": "Adidas",
    "Adidas Howzat": "Adidas",
    "Smith I/O Mag": "Smith",
    "Kookaburra Turf": "Kookaburra",
    "SG Litevate": "SG",
    "Salomon QST 99": "Salomon",
    "Nike Air Zoom Pegasus": "Nike",
    "Gray-Nicolls Test Opener": "Gray-Nicolls",
    "Brooks Ghost": "Brooks",
    "Gray-Nicolls Legend": "Gray-Nicolls",
    "Rossignol Experience 88": "Rossignol",
    "Dukes County International": "Dukes",
    "Anon M4": "Anon",
    "Asics Gel-Kayano": "Asics",
    "New Balance CK10": "New Balance",
    "BalanceFrom Puzzle Mat": "BalanceFrom",
    "Leki Micro Vario": "Leki",
    "SS Ton Gladiator": "SS",
    "Black Diamond Trail": "Black Diamond",
    "New Balance Fresh Foam": "New Balance",
    "Jackson Ultima SoftSkate": "Jackson Ultima",
    "Jerry's Skating World Dress": "Jerry's Skating World",
    "Atomic Vantage 97 Ti": "Atomic",
    "Oakley Flight Deck": "Oakley",
    "ChloeNoel Figure Skating Dress": "ChloeNoel",
    "Riedell 133 Diamond": "Riedell",
    "We Sell Mats Gymnastics Folding Mat": "We Sell Mats"
}

def extract_brand(product_name, brand_mapping):
    return brand_mapping.get(product_name, "Unknown Brand")

# Apply the function to create a new column "Brand" in final_df
final_df["Brand"] = final_df["FamilyLevel2"].apply(lambda x: extract_brand(x, brand_mapping))

display(final_df)

,ClientID,ProductID,TransactionDate,StoreID,StoreCountry,Quantity_in_stock,Category,FamilyLevel1,FamilyLevel2,Universe,ClientSegment,ClientGender,Age,ClientCountry,ClientOptINEmail,ClientOptINPhone,Quantity_sold,SalesNetAmountEuro,product_avg_price_order,avg_price,Weekday,Brand
0,39370740138294,1440540189819119258,2024-12-17 00:00:00+00:00,7704230050291051317,GBR,0.0,Football,Jersey,Nike Away Jersey,Women,LOYAL,F,22.0,GBR,1,1,2,14.99,7.495000,8.337189,Tuesday,Nike
1,39370740138294,1830527890021285361,2024-10-27 00:00:00+00:00,4823099650757441528,GBR,0.0,Football,Shorts,Nike Dri-FIT,Women,LOYAL,F,22.0,GBR,1,1,1,13.99,13.990000,9.181570,Sunday,Nike
2,39370740138294,3095307643986324846,2024-10-28 00:00:00+00:00,4823099650757441528,GBR,0.0,Handball,Ball,Select Ultimate,Men,LOYAL,F,22.0,GBR,1,1,2,78.99,39.495000,53.883987,Monday,Select
3,41168361649132,4786639895536460836,2024-03-03 00:00:00+00:00,7913334853958149044,FRA,3.0,Badminton,Racket,Yonex Astrox 99,Women,LOYAL,F,NaN,FRA,1,1,3,21.98,7.326667,9.759794,Sunday,Yonex
4,118552773044620,7951360260357319889,2024-12-09 00:00:00+00:00,3306498059038628287,USA,1.0,Baseball,Glove,Wilson A2000,Men,LOYAL,F,52.0,USA,1,0,2,38.99,19.495000,26.422090,Monday,Wilson
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
902003,9223352473445645109,1102195885428775766,2025-02-05 00:00:00+00:00,7072849857188684803,ARE,13.0,Badminton,Shuttlecock,Victor Gold Champion,Men,LOYAL,F,NaN,ARE,0,0,1,27.99,27.990000,16.059312,Wednesday,Victor
902004,9223352473445645109,5760088997185117368,2024-05-08 00:00:00+00:00,7072849857188684803,ARE,0.0,Tennis,Ball,Wilson US Open,Men,LOYAL,F,NaN,ARE,0,0,1,26.99,26.990000,15.618155,Wednesday,Wilson
902005,9223352473445645109,5760088997185117368,2024-05-21 00:00:00+00:00,7072849857188684803,ARE,0.0,Tennis,Ball,Wilson US Open,Men,LOYAL,F,NaN,ARE,0,0,1,5.99,5.990000,15.618155,Tuesday,Wilson
902006,9223352473445645109,5760088997185117368,2024-05-23 00:00:00+00:00,7072849857188684803,ARE,0.0,Tennis,Ball,Wilson US Open,Men,LOYAL,F,NaN,ARE,0,0,2,23.99,11.995000,15.618155,Thursday,Wilson
902007,9223363787153601649,6542734401418447353,2024-12-03 00:00:00+00:00,3306498059038628287,USA,6.0,Badminton,Racket,Victor Thruster K,Women,LOYAL,M,NaN,USA,0,0,3,25.98,8.660000,8.876234,Tuesday,Victor

In [12]:
# ===============================
# 2. Compute client-level aggregated features from final_df
# -------------------------------

# 2.1. Percentage of Male Products (using the Universe column; assuming label 'Men')
gender_purchases = (final_df.groupby("ClientID")["Universe"]
                    .value_counts(normalize=True)
                    .unstack(fill_value=0)
                    .reset_index())
if "Men" not in gender_purchases.columns:
    gender_purchases["Men"] = 0
gender_purchases = gender_purchases[["ClientID", "Men"]].rename(columns={"Men": "PercentageMaleProducts"})

# 2.2. Total Amount Spent
total_spent = (final_df.groupby("ClientID")["SalesNetAmountEuro"]
               .sum()
               .reset_index()
               .rename(columns={"SalesNetAmountEuro": "TotalAmountSpent"}))

# 2.3. Total Quantity Bought (using Quantity_sold)
total_quantity = (final_df.groupby("ClientID")["Quantity_sold"]
                  .sum()
                  .reset_index()
                  .rename(columns={"Quantity_sold": "TotalQuantity"}))

# 2.4. Average Amount Per Transaction
avg_transaction = (final_df.groupby("ClientID")["SalesNetAmountEuro"]
                   .mean()
                   .reset_index()
                   .rename(columns={"SalesNetAmountEuro": "AverageAmountPerTransaction"}))

# 2.5. Days Since Last Transaction
last_transaction = (final_df.groupby("ClientID")["TransactionDate"]
                    .max()
                    .reset_index()
                    .rename(columns={"TransactionDate": "LastTransactionDate"}))
last_transaction["DaysSinceLastTransaction"] = (pd.Timestamp.now(tz='UTC') - last_transaction["LastTransactionDate"]).dt.days
last_transaction = last_transaction[["ClientID", "DaysSinceLastTransaction"]]

# 2.6. Most Bought Brand (based on sum of Quantity_sold per brand)
most_bought_brand = (final_df.groupby(["ClientID", "Brand"])["Quantity_sold"]
                     .sum()
                     .reset_index())
most_bought_brand = (most_bought_brand.sort_values(by=["ClientID", "Quantity_sold"], ascending=[True, False])
                     .drop_duplicates(subset=["ClientID"]))
most_bought_brand = most_bought_brand[["ClientID", "Brand"]].rename(columns={"Brand": "MostBoughtBrand"})

# 2.7. Purchase Frequency (average days between transactions per client)
purchase_dates = (final_df.groupby("ClientID")["TransactionDate"]
                  .apply(lambda dates: sorted(pd.to_datetime(dates)))
                  .reset_index())
purchase_dates["AverageFrequency"] = purchase_dates["TransactionDate"].apply(
    lambda dates: np.mean(np.diff(dates)) / np.timedelta64(1, 'D') if len(dates) > 1 else np.inf
)
purchase_dates = purchase_dates[["ClientID", "AverageFrequency"]]

# 2.8. Number of Unique Products Bought
unique_products = (final_df.groupby("ClientID")["ProductID"]
                   .nunique()
                   .reset_index()
                   .rename(columns={"ProductID": "UniqueProductsBought"}))

# 2.9. Amount Spent by Quarter
# First, create a Quarter column in final_df if not already present
final_df["Quarter"] = final_df["TransactionDate"].dt.quarter
amount_by_quarter = (final_df.groupby(["ClientID", "Quarter"])["SalesNetAmountEuro"]
                     .sum()
                     .unstack(fill_value=0))
amount_by_quarter.columns = [f"AmountSpent_Q{col}" for col in amount_by_quarter.columns]
amount_by_quarter = amount_by_quarter.reset_index()

# 2.10. Quantity Bought by Quarter
quantity_by_quarter = (final_df.groupby(["ClientID", "Quarter"])["Quantity_sold"]
                       .sum()
                       .unstack(fill_value=0))
quantity_by_quarter.columns = [f"Quantity_Q{col}" for col in quantity_by_quarter.columns]
quantity_by_quarter = quantity_by_quarter.reset_index()

# 2.11. Amount Spent Percentage per Category
amount_spent_per_category = (final_df.groupby(["ClientID", "Category"])["SalesNetAmountEuro"]
                             .sum()
                             .unstack(fill_value=0))
amount_spent_percentage = amount_spent_per_category.div(amount_spent_per_category.sum(axis=1), axis=0).fillna(0)
amount_spent_percentage.columns = [f"AmountSpentPct_{col}" for col in amount_spent_percentage.columns]
amount_spent_percentage = amount_spent_percentage.reset_index()

In [13]:
# ===============================
# 3. Combine all aggregated features into one DataFrame keyed by ClientID
# -------------------------------
client_features = gender_purchases.merge(total_spent, on="ClientID", how="outer")
client_features = client_features.merge(total_quantity, on="ClientID", how="outer")
client_features = client_features.merge(avg_transaction, on="ClientID", how="outer")
client_features = client_features.merge(last_transaction, on="ClientID", how="outer")
client_features = client_features.merge(most_bought_brand, on="ClientID", how="outer")
client_features = client_features.merge(purchase_dates, on="ClientID", how="outer")
client_features = client_features.merge(unique_products, on="ClientID", how="outer")
client_features = client_features.merge(amount_by_quarter, on="ClientID", how="outer")
client_features = client_features.merge(quantity_by_quarter, on="ClientID", how="outer")
client_features = client_features.merge(amount_spent_percentage, on="ClientID", how="outer")

# Replace any remaining NaNs with sensible defaults
client_features.fillna({
    "PercentageMaleProducts": 0,
    "TotalAmountSpent": 0,
    "TotalQuantity": 0,
    "AverageAmountPerTransaction": 0,
    "DaysSinceLastTransaction": np.inf,
    "AverageFrequency": np.inf,
    "UniqueProductsBought": 0,
    "MostBoughtBrand": "Unknown"
}, inplace=True)

In [14]:
# ===============================
# 4. Merge the client-level features into final_df (by ClientID)
# -------------------------------
final_df = final_df.merge(client_features, on="ClientID", how="left")

# Optional: Display a few rows to verify the new columns
display(final_df)

,ClientID,ProductID,TransactionDate,StoreID,StoreCountry,Quantity_in_stock,Category,FamilyLevel1,FamilyLevel2,Universe,ClientSegment,ClientGender,Age,ClientCountry,ClientOptINEmail,ClientOptINPhone,Quantity_sold,SalesNetAmountEuro,product_avg_price_order,avg_price,Weekday,Brand,Quarter,PercentageMaleProducts,TotalAmountSpent,TotalQuantity,AverageAmountPerTransaction,DaysSinceLastTransaction,MostBoughtBrand,AverageFrequency,UniqueProductsBought,AmountSpent_Q1,AmountSpent_Q2,AmountSpent_Q3,AmountSpent_Q4,Quantity_Q1,Quantity_Q2,Quantity_Q3,Quantity_Q4,AmountSpentPct_Badminton,AmountSpentPct_Baseball,AmountSpentPct_Basketball,AmountSpentPct_Beach,AmountSpentPct_Cricket,AmountSpentPct_Cycling,AmountSpentPct_Football,AmountSpentPct_Golf,AmountSpentPct_Handball,AmountSpentPct_Hockey,AmountSpentPct_Rugby,AmountSpentPct_Running,AmountSpentPct_Skiing,AmountSpentPct_Softball,AmountSpentPct_Tennis,AmountSpentPct_Volleyball
0,39370740138294,1440540189819119258,2024-12-17 00:00:00+00:00,7704230050291051317,GBR,0.0,Football,Jersey,Nike Away Jersey,Women,LOYAL,F,22.0,GBR,1,1,2,14.99,7.495000,8.337189,Tuesday,Nike,4,0.333333,107.97,5,35.99,56,Nike,25.5,3,0.00,0.00,0.0,107.97,0,0,0,5,0.000000,0.0,0.0,0.0,0.0,0.0,0.268408,0.0,0.731592,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
1,39370740138294,1830527890021285361,2024-10-27 00:00:00+00:00,4823099650757441528,GBR,0.0,Football,Shorts,Nike Dri-FIT,Women,LOYAL,F,22.0,GBR,1,1,1,13.99,13.990000,9.181570,Sunday,Nike,4,0.333333,107.97,5,35.99,56,Nike,25.5,3,0.00,0.00,0.0,107.97,0,0,0,5,0.000000,0.0,0.0,0.0,0.0,0.0,0.268408,0.0,0.731592,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
2,39370740138294,3095307643986324846,2024-10-28 00:00:00+00:00,4823099650757441528,GBR,0.0,Handball,Ball,Select Ultimate,Men,LOYAL,F,22.0,GBR,1,1,2,78.99,39.495000,53.883987,Monday,Select,4,0.333333,107.97,5,35.99,56,Nike,25.5,3,0.00,0.00,0.0,107.97,0,0,0,5,0.000000,0.0,0.0,0.0,0.0,0.0,0.268408,0.0,0.731592,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
3,41168361649132,4786639895536460836,2024-03-03 00:00:00+00:00,7913334853958149044,FRA,3.0,Badminton,Racket,Yonex Astrox 99,Women,LOYAL,F,NaN,FRA,1,1,3,21.98,7.326667,9.759794,Sunday,Yonex,1,0.000000,21.98,3,21.98,345,Yonex,inf,1,21.98,0.00,0.0,0.00,3,0,0,0,1.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
4,118552773044620,7951360260357319889,2024-12-09 00:00:00+00:00,3306498059038628287,USA,1.0,Baseball,Glove,Wilson A2000,Men,LOYAL,F,52.0,USA,1,0,2,38.99,19.495000,26.422090,Monday,Wilson,4,1.000000,38.99,2,38.99,64,Wilson,inf,1,0.00,0.00,0.0,38.99,0,0,0,2,0.000000,1.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
902003,9223352473445645109,1102195885428775766,2025-02-05 00:00:00+00:00,7072849857188684803,ARE,13.0,Badminton,Shuttlecock,Victor Gold Champion,Men,LOYAL,F,NaN,ARE,0,0,1,27.99,27.990000,16.059312,Wednesday,Victor,1,1.000000,84.96,5,21.24,6,Wilson,91.0,2,27.99,56.97,0.0,0.00,1,4,0,0,0.329449,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.670551,0.0
902004,9223352473445645109,5760088997185117368,2024-05-08 00:00:00+00:00,7072849857188684803,ARE,0.0,Tennis,Ball,Wilson US Open,Men,LOYAL,F,NaN,ARE,0,0,1,26.99,26.990000,15.618155,Wednesday,Wilson,2,1.000000,84.96,5,21.24,6,Wilson,91.0,2,27.99,56.97,0.0,0.00,1,4,0,0,0.329449,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.670551,0.0
902005,9223352473445645109,5760088997185117368,2024-05-21 00:00:00+00:00,7072849857188684803,ARE,0.0,Tennis,Ball,Wilson US Open,Men,LOYAL,F,NaN,ARE,0,0,1,5.99,5.990000,15.618155,Tuesday,Wilson,2,1.000000,84.96,5,21.24,6,Wilson,91.0,2,27.99,56.97,0.0,0.00,1,4,0,0,0.329449,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.670551,0.0
902006,9223352473445645109,5760088997185117368,2024-05-23 00:00:00+00:00,7072849857188684803,ARE,0.0,Tennis,Ball,Wilson US Open,Men,LOYAL,F,NaN,ARE,0,0,2,23.99,11.995000,15.618155,Thursday,Wilson,2,1.000000,84.96,5,21.24,6,Wilson,91.0,2,27.99,56.97,0.0,0.00,1,4,0,0,0.329449,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.670551,0.0
902007,9223363787153601649,6542734401418447353,2024-12-03 00:00:00+00:00,3306498059038628287,USA,6.0,Badminton,Racket,Victor Thruster K,Women,LOYAL,M,NaN,USA,0,0,3,25.98,8.660000,8.876234,Tuesday,Victor,4,0.000000,25.98,3,25.98,70,Victor,inf,1,0.00,0.00,0.0,25.98,0,0,0,3,1.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0

In [15]:
final_df.columns

Index(['ClientID', 'ProductID', 'TransactionDate', 'StoreID', 'StoreCountry',
       'Quantity_in_stock', 'Category', 'FamilyLevel1', 'FamilyLevel2',
       'Universe', 'ClientSegment', 'ClientGender', 'Age', 'ClientCountry',
       'ClientOptINEmail', 'ClientOptINPhone', 'Quantity_sold',
       'SalesNetAmountEuro', 'product_avg_price_order', 'avg_price', 'Weekday',
       'Brand', 'Quarter', 'PercentageMaleProducts', 'TotalAmountSpent',
       'TotalQuantity', 'AverageAmountPerTransaction',
       'DaysSinceLastTransaction', 'MostBoughtBrand', 'AverageFrequency',
       'UniqueProductsBought', 'AmountSpent_Q1', 'AmountSpent_Q2',
       'AmountSpent_Q3', 'AmountSpent_Q4', 'Quantity_Q1', 'Quantity_Q2',
       'Quantity_Q3', 'Quantity_Q4', 'AmountSpentPct_Badminton',
       'AmountSpentPct_Baseball', 'AmountSpentPct_Basketball',
       'AmountSpentPct_Beach', 'AmountSpentPct_Cricket',
       'AmountSpentPct_Cycling', 'AmountSpentPct_Football',
       'AmountSpentPct_Golf', 'AmountSpentPct_Handball',
       'AmountSpentPct_Hockey', 'AmountSpentPct_Rugby',
       'AmountSpentPct_Running', 'AmountSpentPct_Skiing',
       'AmountSpentPct_Softball', 'AmountSpentPct_Tennis',
       'AmountSpentPct_Volleyball'],
      dtype='object')

In [16]:
pd.set_option('display.max_columns', 500)
display(final_df)

,ClientID,ProductID,TransactionDate,StoreID,StoreCountry,Quantity_in_stock,Category,FamilyLevel1,FamilyLevel2,Universe,ClientSegment,ClientGender,Age,ClientCountry,ClientOptINEmail,ClientOptINPhone,Quantity_sold,SalesNetAmountEuro,product_avg_price_order,avg_price,Weekday,Brand,Quarter,PercentageMaleProducts,TotalAmountSpent,TotalQuantity,AverageAmountPerTransaction,DaysSinceLastTransaction,MostBoughtBrand,AverageFrequency,UniqueProductsBought,AmountSpent_Q1,AmountSpent_Q2,AmountSpent_Q3,AmountSpent_Q4,Quantity_Q1,Quantity_Q2,Quantity_Q3,Quantity_Q4,AmountSpentPct_Badminton,AmountSpentPct_Baseball,AmountSpentPct_Basketball,AmountSpentPct_Beach,AmountSpentPct_Cricket,AmountSpentPct_Cycling,AmountSpentPct_Football,AmountSpentPct_Golf,AmountSpentPct_Handball,AmountSpentPct_Hockey,AmountSpentPct_Rugby,AmountSpentPct_Running,AmountSpentPct_Skiing,AmountSpentPct_Softball,AmountSpentPct_Tennis,AmountSpentPct_Volleyball
0,39370740138294,1440540189819119258,2024-12-17 00:00:00+00:00,7704230050291051317,GBR,0.0,Football,Jersey,Nike Away Jersey,Women,LOYAL,F,22.0,GBR,1,1,2,14.99,7.495000,8.337189,Tuesday,Nike,4,0.333333,107.97,5,35.99,56,Nike,25.5,3,0.00,0.00,0.0,107.97,0,0,0,5,0.000000,0.0,0.0,0.0,0.0,0.0,0.268408,0.0,0.731592,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
1,39370740138294,1830527890021285361,2024-10-27 00:00:00+00:00,4823099650757441528,GBR,0.0,Football,Shorts,Nike Dri-FIT,Women,LOYAL,F,22.0,GBR,1,1,1,13.99,13.990000,9.181570,Sunday,Nike,4,0.333333,107.97,5,35.99,56,Nike,25.5,3,0.00,0.00,0.0,107.97,0,0,0,5,0.000000,0.0,0.0,0.0,0.0,0.0,0.268408,0.0,0.731592,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
2,39370740138294,3095307643986324846,2024-10-28 00:00:00+00:00,4823099650757441528,GBR,0.0,Handball,Ball,Select Ultimate,Men,LOYAL,F,22.0,GBR,1,1,2,78.99,39.495000,53.883987,Monday,Select,4,0.333333,107.97,5,35.99,56,Nike,25.5,3,0.00,0.00,0.0,107.97,0,0,0,5,0.000000,0.0,0.0,0.0,0.0,0.0,0.268408,0.0,0.731592,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
3,41168361649132,4786639895536460836,2024-03-03 00:00:00+00:00,7913334853958149044,FRA,3.0,Badminton,Racket,Yonex Astrox 99,Women,LOYAL,F,NaN,FRA,1,1,3,21.98,7.326667,9.759794,Sunday,Yonex,1,0.000000,21.98,3,21.98,345,Yonex,inf,1,21.98,0.00,0.0,0.00,3,0,0,0,1.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
4,118552773044620,7951360260357319889,2024-12-09 00:00:00+00:00,3306498059038628287,USA,1.0,Baseball,Glove,Wilson A2000,Men,LOYAL,F,52.0,USA,1,0,2,38.99,19.495000,26.422090,Monday,Wilson,4,1.000000,38.99,2,38.99,64,Wilson,inf,1,0.00,0.00,0.0,38.99,0,0,0,2,0.000000,1.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
902003,9223352473445645109,1102195885428775766,2025-02-05 00:00:00+00:00,7072849857188684803,ARE,13.0,Badminton,Shuttlecock,Victor Gold Champion,Men,LOYAL,F,NaN,ARE,0,0,1,27.99,27.990000,16.059312,Wednesday,Victor,1,1.000000,84.96,5,21.24,6,Wilson,91.0,2,27.99,56.97,0.0,0.00,1,4,0,0,0.329449,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.670551,0.0
902004,9223352473445645109,5760088997185117368,2024-05-08 00:00:00+00:00,7072849857188684803,ARE,0.0,Tennis,Ball,Wilson US Open,Men,LOYAL,F,NaN,ARE,0,0,1,26.99,26.990000,15.618155,Wednesday,Wilson,2,1.000000,84.96,5,21.24,6,Wilson,91.0,2,27.99,56.97,0.0,0.00,1,4,0,0,0.329449,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.670551,0.0
902005,9223352473445645109,5760088997185117368,2024-05-21 00:00:00+00:00,7072849857188684803,ARE,0.0,Tennis,Ball,Wilson US Open,Men,LOYAL,F,NaN,ARE,0,0,1,5.99,5.990000,15.618155,Tuesday,Wilson,2,1.000000,84.96,5,21.24,6,Wilson,91.0,2,27.99,56.97,0.0,0.00,1,4,0,0,0.329449,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.670551,0.0
902006,9223352473445645109,5760088997185117368,2024-05-23 00:00:00+00:00,7072849857188684803,ARE,0.0,Tennis,Ball,Wilson US Open,Men,LOYAL,F,NaN,ARE,0,0,2,23.99,11.995000,15.618155,Thursday,Wilson,2,1.000000,84.96,5,21.24,6,Wilson,91.0,2,27.99,56.97,0.0,0.00,1,4,0,0,0.329449,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.670551,0.0
902007,9223363787153601649,6542734401418447353,2024-12-03 00:00:00+00:00,3306498059038628287,USA,6.0,Badminton,Racket,Victor Thruster K,Women,LOYAL,M,NaN,USA,0,0,3,25.98,8.660000,8.876234,Tuesday,Victor,4,0.000000,25.98,3,25.98,70,Victor,inf,1,0.00,0.00,0.0,25.98,0,0,0,3,1.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0

In [17]:
final_df.to_parquet('final_df.parquet', index=False)

In [18]:
import os

# Delete the original CSV file
os.remove('final_dataframe.csv')